name: Build
run-name: Build

on:
  push:
  workflow_dispatch:

env:
  ENABLE_ARTIFACTS_MODE: "false"

jobs:
  build:
    runs-on: windows-2019

    concurrency:
      group: '${{ github.head_ref }}-windows-x64'
      cancel-in-progress: true

    steps:
      - name: test
        shell: bash
        run: |
          echo test
