name: Build Python
run-name: Build Python

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    concurrency:
      group: '${{ github.head_ref }}-windows-x64'
      cancel-in-progress: true

    steps:
      - name: Checkout Python repo
        if: ${{ true }}
        uses: actions/checkout@v3
        with:
          repository: python/cpython
          ref: v3.11.3
          path: 'cpython'

      - name: Build
        if: ${{ true }}
        shell: cmd
        run: |
          cd "%GITHUB_WORKSPACE%\cpython"
          PCbuild\build.bat -e -v -c Release -p Win32

      - name: Create artifacts
        if: ${{ true }}
        shell: cmd
        run: |
          cd "%GITHUB_WORKSPACE%\cpython\PCbuild\win32"
          7z a -aoa -r -saa -sse -t7z -mx9 -mfb=273 -ms -md=64m -mmt=2 -m0=LZMA2 -sdel -y "%GITHUB_WORKSPACE%\python.7z" *

      - name: Upload artifact
        if: ${{ true }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifact_Windows_${{ github.run_id }}
          path: $GITHUB_WORKSPACE/python.7z
