name: Build Python
run-name: Build Python

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    concurrency:
      group: '${{ github.head_ref }}-windows-x64'
      cancel-in-progress: true

    steps:
      - name: Set build directory
        run: |
          $pattern = '[\\]'
          $BUILD_DIR = $env:GITHUB_WORKSPACE -replace $pattern, '/'
          echo "G_WORKSPACE=${BUILD_DIR}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Checkout repo
        if: ${{ false }}
        uses: actions/checkout@v3
        with:
          repository: python/cpython
          ref: v3.11.3
          path: cpython

      - name: Build
        if: ${{ false }}
        shell: cmd
        run: |
          cd "%GITHUB_WORKSPACE%\cpython"
          PCbuild\build.bat -e -v -c Release -p Win32

      - name: Fake Build
        if: ${{ true }}
        shell: bash
        run: |
          mkdir -p "$G_WORKSPACE/cpython/PCbuild/win32"
          cd "$G_WORKSPACE/cpython/PCbuild/win32"
          echo "dummmy" > "test.txt"
          mkdir "mydir"
          echo "dummy" > "mydir/test2.txt"

      - name: Make artifact
        if: ${{ true }}
        shell: bash
        run: |
          cd "$G_WORKSPACE/cpython/PCbuild/win32"
          NAME=Python
          mkdir -p "${G_WORKSPACE}/artifact"
          #7z a -aoa -r -saa -sse -t7z -mx9 -mfb=273 -ms -md=64m -mmt=2 -m0=LZMA2 -sdel -y "${G_WORKSPACE}/artifact/${NAME}" *
          cp -a -v --parents * "${G_WORKSPACE}/artifact"
          echo "artifact_name=$NAME" >> "$GITHUB_ENV"

      - name: ${{ format('Upload artifact {0}', env.artifact_name) }}
        if: ${{ true }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: artifact
          if-no-files-found: error
