name: Build Python
run-name: Build Python

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    concurrency:
      group: '${{ github.head_ref }}-windows-x64'
      cancel-in-progress: true

    steps:
      - name: Checkout Python repo
        if: ${{ true }}
        uses: actions/checkout@v3
        with:
          repository: python/cpython
          ref: v3.11.3
          path: 'cpython'

      - name: Build
        if: ${{ true }}
        shell: cmd
        run: |
          cd "%GITHUB_WORKSPACE%\cpython"
          PCbuild\build.bat -e -M -v -c Release -p Win32

      - name: Test
        shell: cmd
        run: |
          cd "%GITHUB_WORKSPACE%\cpython\win32"
          dir /S
          7z -?

      - name: Upload artifact
        if: ${{ false }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifact_Windows_${{ github.run_id }}
          path: $GITHUB_WORKSPACE/cpython/win32/*
